### Assignment: Binary Classification with Logistic Regression Iris dataset

#### Step 1: Load the Iris dataset

In [1]:
from sklearn.datasets import load_iris

In [2]:
#Extract the feature matrix X and the target vector y.
dataset= load_iris()
dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [3]:
dataset.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [4]:
dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
#Extract the feature matrix X and the target vector y.
X=dataset.data
y=dataset.target

In [6]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

### Step 2: Preprocess the data

To convert this problem into binary classification, create a new target vector y_binary where Iris Setosa (class 0) is labeled as 1, and the other two classes are labeled as 0.

In [8]:
import numpy as np

In [13]:
# Convert to binary classification: Setosa (class 0) vs. others (class 1)
y_binary = np.where(y == 0, 1, 0)

### Step 3: Split the dataset

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(X, y_binary, test_size=0.2)

In [15]:
X_train

array([[4.9, 3.1, 1.5, 0.1],
       [6.5, 3.2, 5.1, 2. ],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 2.8, 4.1, 1.3],
       [5.1, 3.4, 1.5, 0.2],
       [6.1, 3. , 4.9, 1.8],
       [5.6, 3. , 4.1, 1.3],
       [6.4, 3.2, 5.3, 2.3],
       [6.1, 3. , 4.6, 1.4],
       [5.6, 2.9, 3.6, 1.3],
       [4.9, 2.5, 4.5, 1.7],
       [5.2, 2.7, 3.9, 1.4],
       [7.3, 2.9, 6.3, 1.8],
       [5.5, 2.4, 3.8, 1.1],
       [5.1, 2.5, 3. , 1.1],
       [6.7, 3.1, 5.6, 2.4],
       [4.6, 3.6, 1. , 0.2],
       [5.5, 2.4, 3.7, 1. ],
       [4.9, 2.4, 3.3, 1. ],
       [6.1, 2.6, 5.6, 1.4],
       [5.6, 2.5, 3.9, 1.1],
       [5. , 3. , 1.6, 0.2],
       [7.1, 3. , 5.9, 2.1],
       [5.7, 2.6, 3.5, 1. ],
       [6.5, 2.8, 4.6, 1.5],
       [7.4, 2.8, 6.1, 1.9],
       [5.4, 3.7, 1.5, 0.2],
       [6.4, 2.8, 5.6, 2.2],
       [7.6, 3. , 6.6, 2.1],
       [4.8, 3.4, 1.6, 0.2],
       [6.6, 3. , 4.4, 1.4],
       [6.3, 3.4, 5.6, 2.4],
       [6.3, 2.5, 4.9, 1.5],
       [4.8, 3.4, 1.9, 0.2],
       [6.4, 2

In [16]:
y_train

array([1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1])

### Step 4: Define the cost function (logistic loss)

In [17]:
import numpy as np

def logistic_loss(y_true, y_pred):
    n= len(y_true)
    loss=-1/n*np.sum(y_true*np.log(y_pred)+(1-y_true)*np.log(1-y_pred))
    return loss

### Step 5: Define the training function
We will use gradient descent to train our logistic regression model. The gradient descent algorithm updates the model's weights and bias in the direction of decreasing the cost function.

In [18]:
# def train_logistic_regression(X, y, learning_rate, num_iterations, regularization_parameter):
#     #Initialize the model's weights and bias
#     W= np.zeros(X.shape)
#     b=0
#     # Train the model using gradient descent
#     for i in range(num_iterations):
#         # Compute predictions using the sigmoid function
#         y_pred= 1/(1+np.exp(-(X.dot(W)+b)))
        
#         # Compute the gradients of the cost function
#         dW = -1/X.shape * np.sum(X * (y - y_pred))
#         db = -1/X.shape * np.sum(y- y_pred)

#         # Add regularization to the gradients
#         dW += (regularization_parameter/X.shape) * W

#         # Update the model's weights and bias
#         W -= learning_rate * dW
#         b -= learning_rate * db
#     return W, b
        
 

In [19]:
# Step 5: Define the training function
def train_logistic_regression(X, y, learning_rate, num_iterations, regularization_parameter):
    num_samples, num_features = X.shape
    W = np.zeros(num_features)  # Initialize weights
    b = 0  # Initialize bias

    for _ in range(num_iterations):
        # Compute predictions using the sigmoid function
        y_pred = 1 / (1 + np.exp(-(X.dot(W) + b)))

        # Compute gradients
        dW = (1/num_samples) * X.T.dot(y_pred - y)
        db = (1/num_samples) * np.sum(y_pred - y)

        # Regularization term gradients
        dW += (regularization_parameter / num_samples) * W

        # Update weights and bias
        W -= learning_rate * dW
        b -= learning_rate * db

    return W, b

### Step 6: Train the model

In [20]:
learning_rate=0.01
num_iterations = 1000
regularization_parameter = 0.1


In [21]:
W_optimal, b_optimal = train_logistic_regression(X_train, y_train, learning_rate, num_iterations, regularization_parameter)

In [22]:
W_optimal

array([ 0.24759922,  0.89627054, -1.43515088, -0.66903878])

In [23]:
 b_optimal 

0.1788306984944057

In [24]:
def predict_logistic_regression(X_test, W, b):

    # Compute the predictions
    y_pred = 1 / (1 + np.exp(-(X_test.dot(W) + b)))

    # Make binary predictions
    y_pred = np.where(y_pred > 0.5, 1, 0)

    return y_pred
  

In [25]:
# Predict the classes for the test set
y_pred = predict_logistic_regression(X_test, W_optimal,  b_optimal )
y_pred

array([1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0])

In [27]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)

# confusion matrix
confusion_matrix = confusion_matrix(y_test, y_pred)
print('Accuracy:', accuracy)
print('Confusion matrix:')
print(confusion_matrix)



Accuracy: 1.0
Confusion matrix:
[[16  0]
 [ 0 14]]


In [28]:
# Generate the classification report
classification_report = classification_report(y_test, y_pred)

# Print out the accuracy, confusion matrix, and classification report

print('Classification report:')
print(classification_report)

Classification report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        14

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

